### ISSUE TITLE
Readability of Word Literal

### ISSUE THREAD

**Issue by andrewthad** [chessai/bytestring-encodings#1]
In the code, you have:

```haskell
-- | 1000000010000000100000001000000010000000100000001000000010000000
m64 :: Word64
m64 = 9259542123273814144
```

Consider instead writing:

```haskell
-- | 1000000010000000100000001000000010000000100000001000000010000000
m64 :: Word64
m64 = 0x8080808080808080
```

It's much easier to see that this is correct. Alternatively, with the `BinaryLiterals` extension:

```haskell
m64 :: Word64
m64 = 0b1000000010000000100000001000000010000000100000001000000010000000
```

**Comment by chessai** [comment]
I thought about this, but wasn't sure if Haskell had C-style formatting for numeric literals. Thank you for affirming that this is true. I will do this.
