### ISSUE TITLE
name change

### ISSUE THREAD

**Issue by chessai** [chessai/bytestring-encodings#6]
@andrewthad, these are random suggestions:

<ol>
  <li>bytestring-whodunnit</li>
  <li>bytestring-encodings</li>
  <li>bytestring-why-is-this-not-already-in-bytestring</li>
  <li>bytestring-unicode</li>
  <li>bytestring-charset</li>
</ol>

**Comment by andrewthad** [comment]
I'm in favor of `bytestring-charset`, `bytestring-encoding[s]`, `bytestring-char-encoding`, etc. As long as it communicates that it's *textual* encodings that we're talking about and that it welcomes things other than unicode.
